### DISCUSSION TITLE
Automation Examples: Timer Helper

### DISCUSSION THREAD

**Discussion by SvenJachalke** [jeroenterheerdt/HAsmartirrigation#361] [General]
Hi to the community,

first of all: Thanks for the very nice work ... it's always astonishing what you can do with home assistant, thanks to the great community! I really appreciate that!

I would have a suggestions about your automation examples in the wiki. 
In the action section you use the delay action to achieve the needed watering time. Here, I have used a timer helper, which gets the duration from the smart irrigation sensor. Once after the other actions (e.g. opening the valve), the timer is started. Another automation used the timer ending as the trigger to shut off the valve, reset the bucket, etc. Although you have to make two automations (not just a single one) you gain more safety, as the timer continues If home assistants needs to restart for some reasons (shut down, Manuel reboot, docker update, ...). With the delay action all subsequent actions won't be executed. The end could be a flood in your garden? 

Automation 1 (a schedule helper is used as trigger):
```
alias: "GARDEN: START Bewässerungzone 1"
trigger:
  - platform: state
    entity_id:
      - schedule.garden
    to: "on"
condition:
  - condition: numeric_state
    entity_id: sensor.smart_irrigation_zone_1
    above: 0
action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.pumpe
  - service: timer.start
    metadata: {}
    data:
      duration: "{{states('sensor.smart_irrigation_zone_1')}}"
    target:
      entity_id: timer.timer_zone_1
mode: single
```

Automation 2:
```
alias: "GARDEN: STOP Bewässerungszone 1"
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_zone_1
condition:
action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.pumpe
  - service: smart_irrigation.reset_bucket
    metadata: {}
    data: {}
    target:
      entity_id: sensor.smart_irrigation_zone_1
mode: single
```

I hope its reasonable what I have written :D 
If you have any further suggestions, please let me know :)
Greetings

**Comment by jeroenterheerdt** [comment]
that makes sense, what a great idea! I might actually steal this from you :)

**Reply by SvenJachalke** [reply]
Ok nice to hear! 
Yeah of course please steal it ;)

**Comment by zenguru84** [comment]
@SvenJachalke can you please post the schedule helper too?

**Reply by SvenJachalke** [reply]
I'm not really sure if that answers your questions, but I simple added a new helper under Settings --> Devices --> Helpers --> Add Helper --> Timer.
Mine looks like:
<img width="662" alt="Bildschirmfoto 2025-04-04 um 20 55 44" src="https://github.com/user-attachments/assets/381490b2-af3d-404e-8d80-b64a4a4ca9cc" />
Then is this (timer.bewasserungstimer_zone_1) in the automation to set the time from HASmartIrrigation.

**Reply by zenguru84** [reply]
oh, silly me! 
thanks a lot.

**Comment by panrambo** [comment]
Hi @SvenJachalke , thanks for sharing your idea about timers. 

1. Could you please let me know how did you manage to bring more zones firing one after the other? I know that maybe simple question, but I wonder how you recognize in the automation that one finished and the other zone can start. My zones / sprinkle sets cannot run all at the same time due to the water pressure :)

2. Second question, how did you setup the schedule.garden? Is it like twice a week (Tuesday and Thursday) and what time duration did you choose? just for the sprinklers to freely finish?

**Reply by SvenJachalke** [reply]
Hi @panrambo,
sorry for the late reply ... currently I'm playing around with more than one zone. I'm testing some ideas (e.g. having a master timer, etc.), so give some more days and I will share some results!

**Reply by dhaude** [reply]
Morning Sven,
almost one year later now, I am wondering if you derived a solution for multiple Zones.
I'm dealing here with 6 zones and I like your approach - even though I use the Homematic Wired Components, which (until now) never failed to switch OFF.
In the past I also played around with the evaporation factor and used it within SYMCON programmed witrh PHP-Scripts.
I like very much what @jeroenterheerdt did and plan to convert all my zones.

**Reply by SvenJachalke** [reply]
Hi Dieter @dhaude,
I'm very sorry, but I forget to share my "solution" here.

Currently I'm running 4 Zones (3 are displayed in the screenshot and are controlled with Smart Irrigation, the 4th is our greenhouse, which has a simple "water everyday for x minutes" automation). 
<img width="200"  alt="Bildschirmfoto 2026-04-26 um 21 54 45" src="https://github.com/user-attachments/assets/7b9ab0a2-5e9d-40ab-8133-139c64006f5b" />

Every Zone (also defined with Smart Irrigation) has its, "activation switch" and timer (see my post above). 
I have also defined a master timer, which will be set to the longest time of all zones (I have pump in my water tank which has to shut off after the longest zone is finished). 
Once SmartIrrigation has calculated the budget and time, I run a rather complexe automation (I will attach the full yaml), where I set/start the timers with the seconds calculated by SmartIrrigation, e.g.: 
```
action: timer.start
metadata: {}
data:
  duration: "{{states('sensor.smart_irrigation_zone_1_vorgarten_i')}}"
target:
  entity_id: timer.bewasserungstimer_zone_1
```

The mastertimer is set via:
```
action: timer.start
metadata: {}
data:
  duration: >-
    {% set zone4 = state_attr('timer.bewasserungstimer_zone_4', 'duration')%}

    {% set parts = zone4.split(":") %}

    {% set zone4_seconds = (parts[0]|int * 3600) + (parts[1]|int * 60) +
    (parts[2]|int) %}


    {% set zonen = [
      {'sensor': states('sensor.smart_irrigation_zone_1_vorgarten_i') | int, 'aktiv': is_state('input_boolean.bewasserung_zone_1_aktiv', 'on')},
      {'sensor': states('sensor.smart_irrigation_zone_2_vorgarten_ii_terrasse') | int, 'aktiv': is_state('input_boolean.bewasserung_zone_2_aktiv', 'on')},
      {'sensor': states('sensor.smart_irrigation_zone_3_gemusegarten') | int, 'aktiv': is_state('input_boolean.bewasserung_zone_3_aktiv', 'on')},
      {'sensor': zone4_seconds, 'aktiv' : is_state('input_boolean.bewasserung_zone_4_aktiv', 'on')}
    ] %}


    {% set aktive_zeiten = zonen | selectattr('aktiv', 'equalto', true) |
    map(attribute='sensor') | list %}

    {% if aktive_zeiten | length > 0 %}
      {{ aktive_zeiten | max }}
    {% else %}
      0
    {% endif %}
target:
  entity_id: timer.bewasserungstimer_master
```

To review the last watering I save the calculated watering time (because once its executed, I had no idea when and how long the watering time was ;)
To stop the timer (and shot of valves, etc.) a have separate automations, listening on the timer finished event, e.g.:

```
alias: "BEWÄSSERUNG: ZONE 1 AUS"
description: Mittels Zeitplan Helfer und SmartIrrigation Zeitberechnung
triggers:
  - event_type: timer.finished
    event_data:
      entity_id: timer.bewasserungstimer_zone_1
    trigger: event
conditions: []
actions:
  - action: valve.close_valve
    metadata: {}
    data: {}
    target:
      entity_id: valve.garden_valves_zone_1
  - if:
      - condition: state
        entity_id: input_boolean.manuelle_bewasserung
        state: "off"
    then:
      - metadata: {}
        data: {}
        action: smart_irrigation.reset_bucket
        target:
          entity_id: sensor.smart_irrigation_zone_1_vorgarten_i
mode: single
```

I hope, that you could follow this brief description of my approach. If there are any question, I will try to explain ;)
Greetings,
Sven
[HA_ZoneWatering.yaml](https://github.com/user-attachments/files/27105821/HA_ZoneWatering.yaml)
