### DISCUSSION TITLE
Unreliable water source, adjust bucket with real delivery values

### DISCUSSION THREAD

**Discussion by dadino** [jeroenterheerdt/HAsmartirrigation#510] [Q&A]
My irrigation system uses a tank as the only source of water. Sometimes this tank is empty and the pump doesn't run when I turn it on.

I have a sensor in Home Assistant that tells me the daily count of minutes of real water delivery (counting the minutes in which the valve is open and enough current goes to the pump, meaning it's actually pumping).

I'd like to adjust the bucket size after each sequence on Irrigation Unlimited by only adding the corrent amount of mm from the bucket, but I want to be sure I understand the value correctly.

Example numbers, but close to reality:
- area: 100 square meters
- liters/minute: 70
- minutes of real delivery: 2

Do I adjust the bucket by adding 1.4mm (140 liters over 100 square meters)?

I'd have an automation like this:

```
mode: single
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.irrigation_unlimited_c1_s1
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 5
      seconds: 0
conditions: []
actions:
  - action: smart_irrigation.set_bucket
    metadata: {}
    data:
      new_bucket_value: >-
           {{ (states.sensor.smart_irrigation_garden.attributes.bucket | float) + (states('sensor.real_delivery_liters_per_square_meter') | float) }}
    target:
      entity_id: sensor.smart_irrigation_garder

```
