### ISSUE TITLE
Unable to find service smart_irrigation.reset_bucket

### ISSUE THREAD

**Issue by Disane87** [jeroenterheerdt/HAsmartirrigation#109]
Hey, thank you for this nice piece of software! But I got an error in the trace of the automation:
![image](https://user-images.githubusercontent.com/956158/187138328-27eaeee6-edc8-4225-8042-a434e636f8e0.png)

Is this a normal behavior? If not, how can I fix this?
The YAML code:

```yaml
- id: '16548609998223'
  alias: Smart Irrigation
  description: Start Smart Irrigation at 04:00 when the workday sensor is on and run
    it only if the adjusted_run_time is >0 and run it for precisely that many seconds
  trigger:
  - at: 04:00
    platform: time
  condition:
    condition: and
    conditions:
    - above: '0'
      condition: numeric_state
      entity_id: sensor.smart_irrigation_daily_adjusted_run_time
    - above: '0'
      condition: numeric_state
      entity_id: sensor.smart_irrigation_hourly_adjusted_run_time
  action:
  - data: {}
    entity_id: switch.rasenbewasserung_switch
    service: switch.turn_on
  - delay:
      seconds: '{{states("sensor.smart_irrigation_daily_adjusted_run_time")}}'
  - data: {}
    entity_id: switch.rasenbewasserung_switch
    service: switch.turn_off
  - data: {}
    service: smart_irrigation.reset_bucket
```

It's only an edited version of the code on your wiki for a one valve config
