### ISSUE TITLE
In case of daily precipitation level is more than soil can hold

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#110]
I have grass on sandy soil that saturated fully with precipitation level about 12 mm (according trusted soil moisture sensor), so excess of the water just goes bellow the root depth and will not be available for plants. Thus we need to subtract the excess from the bucket in case daily precipitation rate is more than 12 mm/day, right?
Really, we have enormous rain 60 mm in a day two weeks ago and since that the bucket is still 20 mm without reset but the soil dried out after 6 days.
I think an addition of optional entry and automatic correction of bucket can be easily implemented.

**Comment by Andrew-Joakimsen** [comment]
In my installation I've created a virtual sensor to handle this condition:

```
template:
  - name: "Irrigation Daily Rain Rate"
    unique_id: 98038f04-720b-11ed-a1eb-0242ac120002
    state_class: total
    unit_of_measurement: in
    state: >
      {% if state_attr('sensor.smart_irrigation_daily_adjusted_run_time', 'bucket') | int >= 1.2 and states('sensor.daily_rain_rate') | int >= 0.3  %}   
        0.3
      {% elif states('sensor.daily_rain_rate') | int >= 1.1 %}
        1.1
      {% elif states('sensor.daily_rain_rate') | int < 1.1 %}
        {{ states('sensor.daily_rain_rate') }}
      {% else %}
        unavailable
      {% endif %}
```

**Comment by andreid1303** [comment]
Thank you, this is a solution, but not taken evapotranspiration loses of current day into account.

**Comment by NathanSweet** [comment]
Are you saying you want a max bucket size?

**Comment by andreid1303** [comment]
Yes, max bucket size!

**Comment by mcnelson** [comment]
I just realized I have this issue too. After the rainy season, I'm finding my buckets are way too high, and now that we're in sunny weather the irrigation never runs. I have values like about 24.0 in the buckets and they are decreasing like 0.3 - 0.5 per day which is way too slow. 

I could reset the buckets annually, but it would be nice if the script could resolve this on its own. At this rate I don't know if I'd see any irrigation until the middle of summer, which just seems incorrect. A maximum bucket value could help here? Perhaps my config is off?

**Comment by bulburDE** [comment]
I also stumbled across this problem since we had an unusual amount of rain in the last few days. I am trying to solve it with an automation that sets the bucket value to a threshold (20) if the bucket is set to an amount over the threshold.

```
alias: irrigation maximum rasen bucket
description: ""
trigger:
  - platform: event
    event_type: Smart_Irrigation_Rasen_bucketUpd
condition:
  - condition: numeric_state
    entity_id: sensor.smart_irrigation_rasen_daily_adjusted_run_time
    attribute: bucket
    above: 20
action:
  - service: smart_irrigation.smart_irrigation_rasen_set_bucket
    data:
      value: 20
mode: single
```

I just create it and tested it once so I can't say yet if it will work as expected.
