### ISSUE TITLE
smart_irrigation_start not fired

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#140]
In installed this Integration. All went fine also setting up the automation like in the example (see below). I expected that the event smart_irrigation_start would have been fired this morning at sunrise. But nothing happened. Did I misunderstood something? 

```
alias: Smart Irrigation Balkon Wohnzimmer
description: ""
trigger:
  - platform: event
    event_type: smart_irrigation_start
condition:
  - condition: numeric_state
    entity_id: sensor.smart_irrigation_balkon_wohnzimmer_daily_adjusted_run_time
    above: 0
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.bewasserung_balkon
  - delay:
      seconds: >-
        {{states("sensor.smart_irrigation_balkon_wohnzimmer_daily_adjusted_run_time")}}
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.bewasserung_balkon
  - service: smart_irrigation.smart_irrigation_balkon_wohnzimmer_reset_bucket
    data: {}
mode: single
```

This are my settings for BSI

Number of sprinklers 8
Flow 0.2 l
Throughput 1.6 l/min
Reference evapotranspiration [1.66, 2.0, 3.76, 4.99, 6.43, 6.37, 6.41, 5.35, 3.72, 2.55, 1.56, 1.15] mm
Peak evapotranspiration 6.43 mm
Area 4.5 m2
Precipitation rate 21.33 mm/hr
Base schedule index minutes 18.08 min
Auto refresh true
Auto refresh time 23:00
Initial update delay 300 s
Coastal false
Estimate solrad from temp true
