### ISSUE TITLE
smart_irrigation_start_irrigation_all_zones fired multiple times

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#234]
### What happened?

I have 4 auomatic zones. The event 'smart_irrigation_start_irrigation_all_zones' is fired 4 times.

### How to reproduce

React to event 'smart_irrigation_start_irrigation_all_zones'

### Relevant log output

```shell
none
```

### Which version are you running?

 v2023.9.0-beta9

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-a008ef644d0b6e30f0be7b955e0fe1bb.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12519862/config_entry-smart_irrigation-a008ef644d0b6e30f0be7b955e0fe1bb.json.txt)

**Comment by jeroenterheerdt** [comment]
What. First it never happens and now multiple times. Hmpf. I need to look at this again.

**Comment by jeroenterheerdt** [comment]
I found an issue and fixed it in beta13. It fires just once on my end. please try and confirm.

**Comment by gatonero** [comment]
I'm back and happy that the event will only be triggered once.

**Comment by jeroenterheerdt** [comment]
Welcome back!

**Comment by gatonero** [comment]
I'm sorry to reopen this issue. Yesterday I have had some faults with my installation. Today it looks like this:

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/a0da5f1f-6c55-4941-88df-1a63a0f5e210)

**Comment by jeroenterheerdt** [comment]
@gatonero please share a diagnostics file. I am not seeing this on my end.

**Comment by gatonero** [comment]
[config_entry-smart_irrigation-d11d88707d39dd25b4f1a3e93ffd16e7.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12640412/config_entry-smart_irrigation-d11d88707d39dd25b4f1a3e93ffd16e7.json.txt)

**Comment by jeroenterheerdt** [comment]
Thanks. I looked into this a bit yesterday and came to the conclusion that what I ideally wanted to do doesn't work. What I wanted to do is to set the time for the event on any calculate and calculate all or auto calculate. It works fine if you only do auto calculate. Then the event fires just once. Are we OK with me changing the logic to just firing the event when auto calculate happened? I cannot seem to find a way to reliably remove previous event triggers. For example, I have 6 zones and it triggered twice for me. How many zones do you have again @gatonero? Is it also triggering twice or more than that?

**Comment by gatonero** [comment]
I have three automatic zone and one mostly manual for testing purposes. I will have a look tomorrow morning hoping it's not raining today. :)

**Comment by jeroenterheerdt** [comment]
I added an automation that sends a notification. That way it's easy see it happened and you can look at the traces to see when it happened exactly.

**Comment by gatonero** [comment]
This is my automation for it:

```
alias: Start Event smart irrigation
description: ""
trigger:
  - platform: event
    event_type: smart_irrigation_start_irrigation_all_zones
condition: []
action:
  - service: persistent_notification.create
    data:
      message: >-
        Start Event fired at {{ as_timestamp(now()) |
        timestamp_custom("%H:%M:%S", True) }}
mode: single

```
