### ISSUE TITLE
Runs for 25 seconds

### ISSUE THREAD

**Issue by helenclarko** [jeroenterheerdt/HAsmartirrigation#38]
I've probably misconfigured my setup, but I've given it a few days and I continue to see it tries to water for less than a minute.

![image](https://user-images.githubusercontent.com/2774385/84917389-443dce80-b08d-11ea-849b-3fa5240493f3.png)

![image](https://user-images.githubusercontent.com/2774385/84917512-6df6f580-b08d-11ea-925c-61e4eee5df7f.png)

I'm not sure what else you need to see. I guess the automation:

```
- id: '1562542894999'
  alias: Irrigation
  trigger:
  - at: 05:00:00
    platform: time
  condition:
  - above: '0'
    condition: numeric_state
    entity_id: sensor.smart_irrigation_daily_adjusted_run_time
  - above: '0'
    condition: numeric_state
    entity_id: sensor.smart_irrigation_hourly_adjusted_run_time
  action:
  - alias: ''
    data:
      entity_id: switch.irrigation
    service: homeassistant.turn_on
  - delay:
      seconds: '{{states("sensor.smart_irrigation_daily_adjusted_run_time")}}'
  - data:
      entity_id: switch.irrigation
    service: homeassistant.turn_off
  - data: {}
    service: smart_irrigation.smart_irrigation_reset_bucket
```
