### ISSUE TITLE
Add action to update "throughput" attribute via automation

### ISSUE THREAD

**Issue by cappa88** [jeroenterheerdt/HAsmartirrigation#536]
I have built an irrigation controller using an ESP32 with ESPHome, connected to a flow sensor.
Each irrigation zone has a sensor that monitors the water flow throughout the irrigation period and, when the zone turns off, reports the average throughput over the entire duration.
At the moment, it is possible to update the "bucket" attribute via an automation, but there is no similar way to update the "throughput" attribute dynamically.
Being able to do so would greatly improve the system's accuracy and adaptability, for example in cases where the pump's performance may vary over time.

It would be very helpful to have an action available to modify the "throughput" attribute through an automation, similar to what is already possible for the "bucket" value.
This would allow the system to self-calibrate after each irrigation cycle based on real measurements, keeping everything optimized without requiring manual adjustments.

**Comment by jeroenterheerdt** [comment]
@cupertinomiranda is there any chance you can add this as well since you are already working on new services?

**Comment by cupertinomiranda** [comment]
@jeroenterheerdt Sure. Would it be reasonable to actually just add set_zone_data, to which when you would set arguments as optional and you would set the values based on the argument being set?
@cappa88 Can you detail which flow sensor your using. Would want to get the same. 😄

**Comment by cappa88** [comment]
Sure! I'm using the YF-B10 1-inch flow sensor

![Image](https://github.com/user-attachments/assets/50444039-0ff4-4b74-a823-741d22156e7d)

installed together with an emergency automatic valve. Everything is connected, calibrated, and programmed with ESPHome on an ESP32.

![Image](https://github.com/user-attachments/assets/65e5b111-6873-4490-bc80-4389d39243f3)

![Image](https://github.com/user-attachments/assets/aa89e0fd-1eca-48c3-b22f-4ed982d4944d)

![Image](https://github.com/user-attachments/assets/c077985d-19fe-49fb-8ab8-5becd2e53ca5)

![Image](https://github.com/user-attachments/assets/970510df-5af3-4ffa-a17d-285abc4e671b)

The whole setup is designed to work in combination with Smart Irrigation.

**Comment by cupertinomiranda** [comment]
@cappa88 Thanks!
I have a similar setup with esp32 however using some 8 relay board I got from Aliexpress + some other relay board as slaves of the first one using modbus over rs485 to allow to place relay in the field.
https://a.aliexpress.com/_EuGitZY
In total I will have 16 zones, 4 for grass/garden and the remain for trees and backyard.
It would be interesting to collaborate on the esphome programming as well. Do you share the code somewhere?

I am working on some custom cards to integrate on ha. We can possibly collaborate on those as well. Please check the #530 for a preview.

**Comment by jeroenterheerdt** [comment]
I am running an esp8266 with a 8 relay board as well. This is my ESPHOME yaml:

```
esphome:
  name: sprinklercontroller
  friendly_name: sprinklercontroller

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key
  services:
    - service: set_valve_run_duration
      variables:
        duration: int
        valve: int
      then:
        - sprinkler.set_valve_run_duration:
            id: sprinkler_controller
            run_duration: !lambda 'return duration;'
            valve_number: !lambda 'return valve;'
    - service: set_multiplier
      variables:
        multiplier: float
      then:
        - sprinkler.set_multiplier:
            id: sprinkler_controller
            multiplier: !lambda 'return multiplier;'
    - service: start_full_cycle
      then:
        - sprinkler.start_full_cycle: sprinkler_controller
    - service: start_single_valve
      variables:
        valve: int
        duration: int
      then:
        - sprinkler.start_single_valve:
            id: sprinkler_controller
            valve_number: !lambda 'return valve;'
            run_duration: !lambda 'return duration;' #optional
    - service: next_valve
      then:
        - sprinkler.next_valve: sprinkler_controller
    - service: previous_valve
      then:
        - sprinkler.previous_valve: sprinkler_controller
    - service: shutdown
      then:
        - sprinkler.shutdown: sprinkler_controller
ota:
  platform: esphome
  password: !secret OTA_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sprinklercontroller"
    password: !secret fallback_hotspot_password

captive_portal:

switch:
  - platform: gpio
    pin: 5
    id: lawn_sprinkler_valve_sw1
  - platform: gpio
    pin: 4
    id: lawn_sprinkler_valve_sw2
  - platform: gpio
    pin: 0
    id: lawn_sprinkler_valve_sw3
  - platform: gpio
    pin: 14
    id: lawn_sprinkler_valve_sw4
  - platform: gpio
    pin: 12
    id: lawn_sprinkler_valve_sw5
  - platform: gpio
    pin: 13
    id: lawn_sprinkler_valve_sw6
sprinkler:
  - id: sprinkler_controller
    main_switch: "Sprinklers"
    auto_advance_switch: "Sprinklers Auto Advance"
    valve_overlap: 5s #overlap to avoid banging. maybe use valve_open_delay instead?
    multiplier_number: "Sprinklers Multiplier" #s
    repeat_number:  "Sprinklers Repeat" #s
    valves:
      - valve_switch: "Zone 1"
        enable_switch: "Enable Zone 1"
        run_duration_number: "Zone 1 Run Duration" #s
        valve_switch_id: lawn_sprinkler_valve_sw1
      - valve_switch: "Zone 2"
        enable_switch: "Enable Zone 2"
        run_duration_number: "Zone 2 Run Duration" #s
        valve_switch_id: lawn_sprinkler_valve_sw2
      - valve_switch: "Zone 3"
        enable_switch: "Enable Zone 3"
        run_duration_number: "Zone 3 Run Duration" #s
        valve_switch_id: lawn_sprinkler_valve_sw3
      - valve_switch: "Zone 4"
        enable_switch: "Enable Zone 4"
        run_duration_number: "Zone 4 Run Duration" #s
        valve_switch_id: lawn_sprinkler_valve_sw4
      - valve_switch: "Zone 5"
        enable_switch: "Enable Zone 5"
        run_duration_number: "Zone 5 Run Duration" #s
        valve_switch_id: lawn_sprinkler_valve_sw5
      - valve_switch: "Zone 6"
        enable_switch: "Enable Zone 6"
        run_duration_number: "Zone 6 Run Duration" #s
        valve_switch_id: lawn_sprinkler_valve_sw6
sensor:
  - platform: template
    name: "Sprinkler Time Remaining Active Valve"
    lambda: |-
      if (id(sprinkler_controller).time_remaining_active_valve().has_value()) {
        // the controller is running, print the number of seconds remaining
        return id(sprinkler_controller).time_remaining_active_valve().value();
      } else {
        // the controller is NOT running
        return 0;
      }
    update_interval: 5s
    unit_of_measurement: "s"
  - platform: template
    name: "Sprinkler Time Remaining Current Operation"
    lambda: |-
      return id(sprinkler_controller).time_remaining_current_operation();
    update_interval: 5s
    unit_of_measurement: "s"
  - platform: template
    name: "Sprinkler Total Queue Time"
    lambda: |-
      return id(sprinkler_controller).total_queue_time();
    update_interval: 5s
    unit_of_measurement: "s"
  - platform: template
    name: "Sprinkler Total Cycle Time Enabled Incomplete Valves"
    lambda: |-
      return id(sprinkler_controller).total_cycle_time_enabled_incomplete_valves();
    update_interval: 5s
    unit_of_measurement: "s"
  - platform: template
    name: "Sprinkler Total Cycle Time Enabled Valves"
    lambda: |-
      return id(sprinkler_controller).total_cycle_time_enabled_valves();
    update_interval: 5s
    unit_of_measurement: "s"
  - platform: template
    name: "Sprinkler Total Cycle Time All Valves"
    lambda: |-
      return id(sprinkler_controller).total_cycle_time_all_valves();
    update_interval: 5s
    unit_of_measurement: "s"
```
